// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBook.Ledana;

#nullable disable

namespace PhoneBook.Ledana.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20260418062659_AddedCategories")]
    partial class AddedCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhoneBook.Ledana.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Friends"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Work"
                        });
                });

            modelBuilder.Entity("PhoneBook.Ledana.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Email = "dylan12@abc.com",
                            FirstName = "Bob",
                            LastName = "Dylan",
                            PhoneNumber = "+355691234567"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Email = "aster12@abc.com",
                            FirstName = "Amelia",
                            LastName = "Aster",
                            PhoneNumber = "+355691234123"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Email = "marti12@abc.com",
                            FirstName = "Loredana",
                            LastName = "Marti",
                            PhoneNumber = "+355694564567"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Email = "griffin12@abc.com",
                            FirstName = "Luiza",
                            LastName = "Griffin",
                            PhoneNumber = "+355691201467"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Email = "scott12@abc.com",
                            FirstName = "Daniel",
                            LastName = "Scott",
                            PhoneNumber = "+355690230123"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Email = "demarti12@abc.com",
                            FirstName = "Vivian",
                            LastName = "DeMarti",
                            PhoneNumber = "+355694064061"
                        });
                });

            modelBuilder.Entity("PhoneBook.Ledana.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Please call me ASAP",
                            ContactId = 4,
                            Subject = "Urgent"
                        },
                        new
                        {
                            Id = 2,
                            Body = "When should we be at the party?",
                            ContactId = 1,
                            Subject = "Party time"
                        },
                        new
                        {
                            Id = 3,
                            Body = "We will have a meeting about the project Friday at noon",
                            ContactId = 2,
                            Subject = "Project boy"
                        });
                });

            modelBuilder.Entity("PhoneBook.Ledana.Models.SMS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("SMSs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactId = 3,
                            Subject = "Call me when you can"
                        },
                        new
                        {
                            Id = 2,
                            ContactId = 2,
                            Subject = "I just left work, I'll be home in 10"
                        },
                        new
                        {
                            Id = 3,
                            ContactId = 5,
                            Subject = "Stop calling me!!!! :)"
                        });
                });

            modelBuilder.Entity("PhoneBook.Ledana.Models.Contact", b =>
                {
                    b.HasOne("PhoneBook.Ledana.Models.Category", "Category")
                        .WithMany("Contacts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PhoneBook.Ledana.Models.Email", b =>
                {
                    b.HasOne("PhoneBook.Ledana.Models.Contact", "Contact")
                        .WithMany("Emails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("PhoneBook.Ledana.Models.SMS", b =>
                {
                    b.HasOne("PhoneBook.Ledana.Models.Contact", "Contact")
                        .WithMany("SMSs")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("PhoneBook.Ledana.Models.Category", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("PhoneBook.Ledana.Models.Contact", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("SMSs");
                });
#pragma warning restore 612, 618
        }
    }
}
